// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
'use strict';

const AdMob = {
  ready() {},
  start() {},
  adLoad() {},
  adShow() {},
  adHide() {},
  adCreate() {},
  configure() {},
  adIsLoaded() {},
  setAppMuted() {},
  setAppVolume() {},
  bannerConfig() {},
  configRequest() {},
  requestTrackingAuthorization() {},
};

// eslint-disable-next-line node/no-missing-require
require('cordova/exec/proxy').add('AdMob', AdMob);
